spring:
  application:
    names: os1-intern-application
  data:
    mongodb:
      database: Library
      uri: mongodb://localhost:27017/Library

server:
  port: 8080

root:
  username: root
  password: root
  email: root@gmail.com
  role: root
